blog/urls.py
from django.urls import path
from blog.views import post_details, render_posts

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_details, name="post_details")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)
    
    def __str__(self) -> str:
        return f'{self.title}'

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self) -> str:
        return f"{self.title}, Description:{self.description}"

blog/views.py
from django.shortcuts import render, get_object_or_404

from blog.models import Post

# Create your views here.

def render_posts(requests):
    posts = Post.objects.all()
    return render(requests, 'posts.html', {'posts':posts})

def post_details(requests, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(requests, 'post_details.html', {"post":post})

portfolio/views.py
from django.shortcuts import render

from portfolio.models import Project

# Create your views here.

def home(request):
    projects = Project.objects.all()


    return render(request, 'home.html',{'projects':projects})

blog/templates/post_details.html
{% extends 'layout.html' %}

{% block content %}

<div class="my-4">
    <h1> {{post.title}}</h1>
    <l1 class="text muted">{{post.date|date:'F jS Y'}}</li>
    <p>{{post.description}}</p>
</div>

<div class="my-4">
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid" />
</div>

{% endblock  %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

<h1>Posts</h1>

{% for post in posts %}
<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid" />
                
                <h2>{{post.title}}</h2>
                <l1>{{post.date|date:'M d Y'|upper}}</li>
                <p>{{post.description|truncatechars:100}}</p>

                <a href="{% url 'blog:post_details' post.id %}" class="btn btn-primary btn-sm">Leer</a>    
                    
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock  %}

portfolio/templates/home.html
{% extends 'layout.html' %} {% block content %} {% load static %}

<header class="row bg-black ">
  <div class="col-md-4">
    <img src="{% static 'portfolio/perfil.png' %}" class="img-fluid py-4" />
  </div>

  <div class="col-md-8 my-auto text-center">
    <h1>I'm <strong> Armando Tinoco </strong></h1>
    <h1>Python Developer</h1>
    <h7>Hi!! and wellcome!!</h7>
    <p class="text-center">
      I am a back-end Web Developer with great
      ability to design and develop timely
      strategies, I have +3 years experience in Python, Django,
      JavaScript, AWS and Node js, with
      knowledge of agile SCRUM
      methodologies and great analytical
      skills to solve problems effectively
    </p>
    <a
      class="btn btn-primary btn-sn"
      href="{% static 'portfolio/CV_ATP.pdf' %}"
      target="_blanc"
      >Download Cv</a
    >
  </div>
</header>

<div class="row my-4 text-center">
  <h3>My Projects</h3>

  {% for project in projects %}
  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <div class="card-body">
        <img
          src="{{project.image.url}}"
          alt="{{project.title}}"
          class="img-fluid"
        />
        <h2>{{project.title}}</h2>
        <p>{{project.description}}</p>
        {% if project.url %}
        <a href="{{project.url}}" class="btn btn-dark rounded-0 btn-sm" target="_blanc">{{project.url}}</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %} {% endblock %}
</div>

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>AT Portfolio</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'main.css' %}" />
  </head>
  <body class="text-light">
    {% include 'partials/navbar.html' %}

    <div class="container">{% block content %} {% endblock %}</div>

    <script src="" async defer></script>
  </body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="{% url "home"%}">Armando Tinoco</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center-">
          <a
            class="btn btn-primary btn-sn"
            href="{% static 'portfolio/CV_ATP.pdf' %}"
            target="_blanc"
            >Download Cv</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>